apiVersion: apps/v1
kind: Service
metadata:
    name: redis-service
    labels:
        app: redis
    spec:
        selector:
            app: redis
        ports:
        - protocol:
        port: 6379
        targetPort: 6379
        type: ClusterIP