name: Go
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPO_OWNER: neuhelen
  IMAGE_NAME: neuhelen/simple-fortune-cookie

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Setup redis
        uses: supercharge/redis-github-action@1.7.0
        with: 
          redis-version: latest
          
      - name: Install redis cli # so we can test the server
        run: sudo apt-get install -y redis-tools

      - name: Verify that redis is up
        run: redis-cli ping
        
      - name: Build backend
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go build
          
      - name: build frontend
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go build
          
      - name: go test frontend
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go test
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./backend-docker
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/backend:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./frontend-docker
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/frontend:latest
