name: production
on:
  workflow_run:
    workflows: development  # Name of the first workflow
    types:
      - completed

env:
  REGISTRY: ghcr.io
  REPO_OWNER: neuhelen
  IMAGE_NAME: neuhelen/simple-fortune-cookie

jobs:
  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: pull backend
        run: docker pull ghcr.io/neuhelen/backend:latest
  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: pull backend
        run: docker pull ghcr.io/neuhelen/frontend:latest
  docker-compose:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: hoverkraft-tech/compose-actions@v2.0.1
        with:
          compose-file: "docker-compose.yml"
