name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7, 8]
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          image: redis
      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go build
      - name: build
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go build
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go run backend
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go run frontend
