name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go build
      - name: build
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go build
      - name: list
        run: go list -m all
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go run
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go run
