name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v /home/runner/work/simple-fortune-cookie/simple-fortune-cookie/backend
      - name: build
        run: go build -v /home/runner/work/simple-fortune-cookie/simple-fortune-cookie/frontend
      - name: go run
        run: go run backend
      - name: go run
        run: go run frontend
