name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [1.8.5]
        github: [1.7.0]
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Setup redis
        uses: supercharge/redis-github-action@${{ matrix.github }}
        with: 
          redis-version: ${{ matrix.redis-version }}

      - name: Install redis cli # so we can test the server
        run: sudo apt-get install -y redis-tools

      - name: Verify that redis is up
        run: redis-cli ping
      - name: Start Redis
        uses: supercharge/redis-github-action@{{ matrix.github }}
        with:
          redis-version: ${{ matrix.redis-version }}
          image: redis
      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go build
      - name: build
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go build
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          go run backend
      - name: go run
        working-directory: ${{ github.workspace }}
        run: |
          cd frontend
          go run frontend
